### PR TITLE
Minor improvment of the display in the timeline.

### PR DESCRIPTION
**Pull request by Dragnucs**

### CODE REVIEW

**Comment by yvolk** [comment]
@Dragnucs I compared layout before and after changes (see below), and I cannot tell that the layout looks better after the change.
screenshot_2016-01-06-10-10-31
After the proposed change:
screenshot_2016-01-06-10-21-27

**Comment by Dragnucs** [comment]
Then add even more margin to avatars.

**Comment by yvolk** [comment]
I agree, margins of avatars should be, at least, equal?!
Now the top, left and rigth margins are different...

**Comment by Dragnucs** [comment]
Not necessarily equal, their distance to the text can be different from 
the one to the screen borders and other posts.

Also, while at it, can you please chose a colour for the posts 
separation lines closer to the background. A line of a dark colour on 
dark background, and of a light colour for a light background.

**Comment by vinzv** [comment]
+1 for the more transparent or darker separation line!

**Comment by yvolk** [comment]
@vinzv @Dragnucs Let's create a new issue for the style/color of separator lines and discuss and agree upon exact values there?!

**Comment by Dragnucs** [comment]
OK.

**Comment by asterismo** [comment]
It would awesome to have the image previews in posts even if the link inage ends in / and not in .jpg or image known extension. cheers, great app, lovin it.

**Comment by yvolk** [comment]
@asterismo Please create a separate issue for that with concrete and reproducible example, and a screenshot maybe...

**Pull request closed without merging**
