### PR TITLE
new website design

### PR DESCRIPTION
**Pull request by vinzv**
* moved current design to folder old
* added new design

to do:
* merge changelog xml code from old design

### CODE REVIEW

**Comment by yvolk** [comment]
Thank you! 
I don't want to merge this request to master since it breaks existing links, at least to a changelog. Will do this via file copying...

**Comment by yvolk** [comment]
1. I agree that we don't need additional andstatus folder. 
2. Stylesheet should be external, one for all pages (like it was earlier).

**Comment by vinzv** [comment]
You stated reasonable issues. I fixed them in a new commit, see pull request.

**Comment by yvolk** [comment]
Hi @vinzv , I pulled your changes into another branch, where we can complete new design. Please see https://github.com/andstatus/andstatus/tree/web-design-243

**Pull request closed without merging**
