### PR TITLE
Fix typo: "Mehr erfaren" -> "Mehr erfahren"

### PR DESCRIPTION
**Pull request by EHJ-52n**

### CODE REVIEW

**Comment by yvolk** [comment]
Hi @EHJ-52n , we don't change localization directly in this repository. 
Could you please suggest the same changes to https://crowdin.com/project/andstatus

**Comment by EHJ-52n** [comment]
Already reported 5 days ago: https://crowdin.com/translate/andstatus/4/enus-de#q=splash_button_learn_more

**Comment by yvolk** [comment]
Thank you, so I see that the corrected translation is already there. 
I will certainly update all translations from Crowdin before next release. 
BTW, are you building AndStatus from its source code?

**Comment by EHJ-52n** [comment]
No, I am just thinking about establishing GNU Social in our company for internal communication. I forked the repo to easy contribute the typo fix update.

**Pull request closed without merging**
