### PR TITLE
added Quitter.{es,zone} and fixed .is max-length

### PR DESCRIPTION
**Pull request by mmn**
Did I do this right? ;)

### CODE REVIEW

**Comment by moshpirit** [comment]
I've tried to add my quitter.zone account, but still can't sing in. Probably because the server.

I think you did it right, but maybe changing Quitter to Quitter.se should be right too.
Btw, why isn't enabled HTML on Quitter.se?

**Comment by moshpirit** [comment]
I have two Quitters: quitter.se and Quitter. I can't delete Quitte, only quitter.se, what's happening?
Using the last beta apk

**Comment by yvolk** [comment]
You can delete only a Microblogging system, which doesn't have any data...

**Comment by yvolk** [comment]
@mmn Pull requests should be tested. This one will not work at least because of the space in the Microblogging system name :-)
2. Max-length should not be set for these systems, I think. Because AndStatus can get these values via API (get config...), see the method
MbConfig getConfig()
at https://github.com/andstatus/andstatus/blob/master/app/src/org/andstatus/app/net/social/ConnectionTwitterGnuSocial.java

**Comment by yvolk** [comment]
Thank you, @mmn!
I added these two instances, as you suggested. But I'm refusing the pull request as it is buggy. 
Next time please test your suggestions using this simple instruction: https://github.com/andstatus/andstatus/wiki/Building-AndStatus-from-Source-code-on-your-Android-device-using-AIDE-application

1. Please test connection to Quitter.es using the latest commit. I couldn't since the registration is closed.
2. Connection to Quitter Zone doesn't work, hope to solve it with a help of its admins, see https://quitter.zone/notice/15129

**Comment by moshpirit** [comment]
I can sing in using a quitter.es account :)
Holger (holger@quitter.zone) couldn't change anything until he went out of his office 2 hours ago, I hope he's working on it.

**Comment by mmn** [comment]
>1. Please test connection to Quitter.es using the latest commit. I
>couldn't since the registration is closed.

I reopened registrations for a while. Hopefully I won't have to shut them down tomorrow during the more popular hours ;)

Meanwhile I'll see if I can setup a build environment. Will let you know if I succeeded and also could connect.

>2. Connection to Quitter Zone doesn't work, hope to solve it with a
>help of its admins, see https://quitter.zone/notice/15129

Hm, yes. holger seems to be having some troubles. hopefully they'll work out. I'll see if I can help him.

-- 
Mikael Nordfeldth
XMPP/mail: mmn@hethane.se

**Pull request closed without merging**
