### PR TITLE
Added short-desc for new translation - Norwegian

### PR DESCRIPTION
**Pull request by fxdwg**
Short description - new translation in progress -  Norwegian

### CODE REVIEW

**Comment by yvolk** [comment]
Please provide translation updates via https://crowdin.com/project/andstatus

**Comment by fxdwg** [comment]
blah ...

**Comment by fxdwg** [comment]
FYI norwegian translation done -> https://crowdin.com/project/andstatus

**Comment by yvolk** [comment]
Thanks, I see ☺

**Comment by yvolk** [comment]
v.20.1. Published at the Open Beta testing channel, please opt in here: https://play.google.com/apps/testing/org.andstatus.app

**Comment by fxdwg** [comment]
Ok - tx.

**Comment by fxdwg** [comment]
Opted in - how do I get the v20.1 ?

**Comment by moshpirit** [comment]
[This way](https://github.com/andstatus/andstatus/wiki/Developerfaq)

**Comment by fxdwg** [comment]
:-)

**Comment by fxdwg** [comment]
Hmm got the v20.1 - but how to change the language ? @yvolk - mine is still showing english. The device is using Norwegian.

**Comment by yvolk** [comment]
Settings->Appearance->Application language, see #201 also.
BTW, I'm pushing 20.2 to Beta channel with latest updates...

**Comment by fxdwg** [comment]
tx - @yvolk works ok. verifying the language now in the app now....

**Comment by moshpirit** [comment]
Could you please share the apk?

**Comment by yvolk** [comment]
@fxdwg BTW, Android v.5.1 emulator set to Norwegian language detects Norwegian language in AndStatus automatically.

**Comment by fxdwg** [comment]
@yvolk hmm ok. I've testing AndStatus on a Nexus 5 with android v6 (Marshmallow), which did not pickup my norwegian default configuration. Had to choose language in AndStatus

**Comment by yvolk** [comment]
I will test this on hardware devices and try to change resources' suffix from -nb to nb-rNO
as was done here https://github.com/plusonelabs/calendar-widget/issues/109

**Comment by yvolk** [comment]
It appears that -nb suffix is correct. Will publish v.20.3. shortly

**Pull request closed without merging**
