### PR TITLE
Added Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
:)

### CODE REVIEW

**Comment by yvolk** [comment]
Hello @Vistaus 
Thank you for the contribution,
but could you add the translation at this site: https://crowdin.com/project/andstatus/nl#
Please :-)

**Comment by Vistaus** [comment]
@yvolk Done! :-)

**Comment by yvolk** [comment]
Thank you!

**Comment by yvolk** [comment]
@Vistaus I released v.39.00 with your translation. Please check! #456

**Pull request closed without merging**
