### PR TITLE
Add screenshots for F-Droid

### PR DESCRIPTION
**Pull request by jaller94**
This PR aims to add screenshots to the listing in the F-Droid store.
Descriptions/ images can either be added to this repo or to https://gitlab.com/fdroid/fdroiddata/tree/master/metadata

The files get updated to the F-Droid store on a release, not by merging this PR.

- [ ] A feature image can be added by adding the file `./fastlane/metadata/android/en-US/images/featureGraphic.png`.

How to add screens to F-Droid: https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

Fastlane's doc: https://docs.fastlane.tools/actions/supply/#images-and-screenshots

### CODE REVIEW

**Comment by yvolk** [comment]
Hello @jaller94 
Thank you very much for the contribution. The https://github.com/fastlane/fastlane really looks like a unifying way to store metadata for both F-Droid and Google Play, both of which #AndStatus uses.
I was especially impressed by the tool's (advertized...) feature "fastlane supply init: download metadata for an existing app to a local directory", which I understand as ability to initialize metadata with what is already stored in Play Store...
As you may know, AndStatus already has quite a lot of screenshots in Google Play Store https://play.google.com/store/apps/details?id=org.andstatus.app plus several (duplicating them...) - in AndStatus Wiki repository, see: https://github.com/andstatus/andstatus/wiki
It would be good to synchronize them, store in a single location and make available for all usages.
This is why I think that I should start with importing existing images / metadata from Google Play Store, and only after that update that images (if necessary) with your contributed screenshots.
?!

**Comment by jaller94** [comment]
Hi @yvolk.
The screenshots I uploaded are the ones from the Google Play store.
Fastlane does support to store metadata like `short_description.txt`, `long_description.txt`, `title.txt` and `video.txt`. It also supports update notes which work in both stores.

In the wiki the images could be linked from the master branch. I guess it would get a little awkward if new features are not yet in the master branch but already have an entry in the wiki (if that exists for this AndStatus).

**Comment by yvolk** [comment]
Ok, so I got that you copied from Play Store screenshots for one language. But we need all existing screenshots to be migrated, so I will try to do this using the Fastlane tool and my credentials.
Currently metadata for short_description.txt and long_description.txt is stored inside /docs folder of the repository, so it should be moved to the same unified place also (or maybe it will be copied automatically from Play Store, I need to test this...)

**Comment by jaller94** [comment]
`fastlane supply init` is an eay way of copying the data from the Google Play Store into the fastlane folder structure, if you want to go all the way.

https://docs.fastlane.tools/getting-started/android/setup/

**Comment by jaller94** [comment]
Hi @yvolk,
did you find some time to test the import from the Google Play Store?

I would be interested in your experience of importing lots of localized content.

**Comment by yvolk** [comment]
Hi @jaller94 , I tried to install Fastlane on Windows + Linux subsystem for Windows - it fails on building some native libraries. So it looks like Fastlane currently is for Mac users mostly :-(
Anyway, as I read from docs, importing image files from Google Play is impossible due to Play Store API limitation...

**Comment by yvolk** [comment]
Two years later I checked if Fastlane is supported on non macOS platforms.
Still no. For this means that there is no point in following its file structure to store metadata, including screenshots.
More details on Fastlane - in this thread: https://github.com/fastlane/fastlane/issues/11687

**Comment by KerstinMaur** [comment]
You can create the folder structure using any operating system. F-Droid will recognize it and use it for its listing. A really working fastlane is not necessary for F-Droid, or am I missing something? 🤔

**Comment by yvolk** [comment]
@KerstinMaur Fortunately, I found better solution: there IS another tool to manage metadata in Google Play that is supported now by F-Droid: https://github.com/Triple-T/gradle-play-publisher
It alloweded me to import automatically existing metadata from Google Play store, and now this metadata is used by F-Drois. I mean you can see the same screenshots at F-Droid web site: https://f-droid.org/packages/org.andstatus.app/

**Pull request closed without merging**
